#!/bin/sh
# Currently, this file sets environment variables and little else

# These envvars are likely to remain consistent across machines
command -v moar 1>/dev/null 2>&1 && export PAGER="moar --no-linenumbers"
export EDITOR="/usr/bin/emacsclient -t -a nvim"
export VISUAL="/usr/bin/emacsclient -c -a emacs"
export XCOMPOSEFILE="$HOME/.config/x11/compose"
export BAT_THEME="gruvbox-dark"
SSH_AUTH_SOCK="/run/user/$(id -u)/keyring/ssh"
export SSH_AUTH_SOCK
export PASSWORD_STORE_DIR=~/.local/share/password-store
export QT_QPA_PLATFORMTHEME=qt5ct
export XCURSOR_SIZE=16

# Make sure the path includes any of my user bins

for userbin in "dotfiles/bin" ".local/bin" ".emacs.d/bin" ".cargo/bin" "scripts"; do
    case $PATH in
        *${userbin}*) : ;;
        *)
            PATH="$HOME/$userbin:$PATH"
            ;;
    esac
done

# Source machine-local envvars
# shellcheck disable=SC1091
[ -f "$HOME/.profile.loc" ] && . "$HOME/.profile.loc"
