;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;;; *** THIS FILE IS AUTOMATICALLY GENERATED. Edit =config.org= to make changes.

(setq shell-file-name (executable-find "bash"))
(setq-default vterm-shell (executable-find "fish"))
(setq-default explicit-shell-file-name (executable-find "fish"))

(setq user-full-name "Sean Gallagher"
      user-mail-address "sean@gallaghersw.dev")

(setq! doom-theme 'doom-gruvbox
       doom-gruvbox-dark-variant "hard")

(setq! doom-font (font-spec :family "FiraCode Nerd Font" :size 14 :weight 'medium)
       doom-variable-pitch-font (font-spec :family "Fira Sans")
       doom-symbol-font (font-spec :family "JuliaMono" :size 14))
(custom-set-faces!
  '(highlight-indent-guides :foreground "#3c3836")
  '(fill-column-indicator :foreground "#3c3836"))

(use-package! mixed-pitch
  :config
  (setq mixed-pitch-set-height t)
  (set-face-attribute 'variable-pitch nil :height 118))

(after! ligature
  ;; Enable the "www" ligature in every possible major mode
  (ligature-set-ligatures 't '("www"))
  ;; Enable traditional ligature support in eww-mode, if the
  ;; `variable-pitch' face supports it
  (ligature-set-ligatures 'eww-mode '("ff" "fi" "ffi"))
  ;; Enable all Cascadia and Fira Code ligatures in programming modes
  (ligature-set-ligatures 'prog-mode
                          '(;; == === ==== => =| =>>=>=|=>==>> ==< =/=//=// =~
                            ;; =:= =!=
                            ("=" (rx (+ (or ">" "<" "|" "/" "~" ":" "!" "="))))
                            ;; ;; ;;;
                            (";" (rx (+ ";")))
                            ;; && &&&
                            ("&" (rx (+ "&")))
                            ;; !! !!! !. !: !!. != !== !~
                            ("!" (rx (+ (or "=" "!" "\." ":" "~"))))
                            ;; ?? ??? ?:  ?=  ?.
                            ("?" (rx (or ":" "=" "\." (+ "?"))))
                            ;; %% %%%
                            ("%" (rx (+ "%")))
                            ;; |> ||> |||> ||||> |] |} || ||| |-> ||-||
                            ;; |->>-||-<<-| |- |== ||=||
                            ;; |==>>==<<==<=>==//==/=!==:===>
                            ("|" (rx (+ (or ">" "<" "|" "/" ":" "!" "}" "\]"
                                            "-" "=" ))))
                            ;; \\ \\\ \/
                            ("\\" (rx (or "/" (+ "\\"))))
                            ;; ++ +++ ++++ +>
                            ("+" (rx (or ">" (+ "+"))))
                            ;; :: ::: :::: :> :< := :// ::=
                            (":" (rx (or ">" "<" "=" "//" ":=" (+ ":"))))
                            ;; // /// //// /\ /* /> /===:===!=//===>>==>==/
                            ("/" (rx (+ (or ">"  "<" "|" "/" "\\" "\*" ":" "!"
                                            "="))))
                            ;; .. ... .... .= .- .? ..= ..<
                            ("\." (rx (or "=" "-" "\?" "\.=" "\.<" (+ "\."))))
                            ;; -- --- ---- -~ -> ->> -| -|->-->>->--<<-|
                            ("-" (rx (+ (or ">" "<" "|" "~" "-"))))
                            ;; *> */ *)  ** *** ****
                            ("*" (rx (or ">" "/" ")" (+ "*"))))
                            ;; www wwww
                            ("w" (rx (+ "w")))
                            ;; <> <!-- <|> <: <~ <~> <~~ <+ <* <$ </  <+> <*>
                            ;; <$> </> <|  <||  <||| <|||| <- <-| <-<<-|-> <->>
                            ;; <<-> <= <=> <<==<<==>=|=>==/==//=!==:=>
                            ;; << <<< <<<<
                            ("<" (rx (+ (or "\+" "\*" "\$" "<" ">" ":" "~"  "!"
                                            "-"  "/" "|" "="))))
                            ;; >: >- >>- >--|-> >>-|-> >= >== >>== >=|=:=>>
                            ;; >> >>> >>>>
                            (">" (rx (+ (or ">" "<" "|" "/" ":" "=" "-"))))
                            ;; #: #= #! #( #? #[ #{ #_ #_( ## ### #####
                            ("#" (rx (or ":" "=" "!" "(" "\?" "\[" "{" "_(" "_"
                                         (+ "#"))))
                            ;; ~~ ~~~ ~=  ~-  ~@ ~> ~~>
                            ("~" (rx (or ">" "=" "-" "@" "~>" (+ "~"))))
                            ;; __ ___ ____ _|_ __|____|_
                            ("_" (rx (+ (or "_" "|"))))
                            ;; Fira code: 0xFF 0x12
                            ("0" (rx (and "x" (+ (in "A-F" "a-f" "0-9")))))
                            ;; Fira code:
                            "Fl"  "Tl"  "fi"  "fj"  "fl"  "ft"
                            ;; The few not covered by the regexps.
                            "{|"  "[|"  "]#"  "(*"  "}#"  "$>"  "^="))
  (setq! +ligatures-extra-symbols
         '(:name "≔"  :src_block "«"  :src_block_end "»"  :quote "“"  :quote_end "”"
           ;; Functional
           :lambda "λ"  :def "ƒ"  :composition "∘"  :map "↦"
           ;; Types
           :null "∅"  :true "⊤"  :false "⊥"  :int "ℤ"
           :float "ℝ"  :str "𝕊"  :bool "⊤⊥"  :list "[]"
           ;; Flow
           :not "¬"  :in "∈"  :not-in  "∉"  :and "∧"  :or "∨"
           :for "∀"  :some "∃"  :return "⟼"  :yield "⟻"
           ;; Other
           :union "⋃"  :intersect "∩"  :diff "∖"  :tuple "⨂"
           :pipe ""  :dot "•"))
  (global-ligature-mode t))

(setq display-line-numbers-type 'relative)
(setq! doom-modeline-buffer-file-name-style 'truncate-with-project
       fill-column 88)  ;; Make sure the DeLorean is up to 88 mph
(global-display-fill-column-indicator-mode)
(setq! indent-tabs-mode nil
       adaptive-wrap-extra-indent 6)

(defun python-mode-tweaks () (rainbow-delimiters-mode 1) (rainbow-mode 1))
(add-hook! 'python-mode-hook 'python-mode-tweaks)

(defun json-mode-tweaks ()
  (display-fill-column-indicator-mode 0)
  (mixed-pitch-mode 0)
  (+word-wrap-mode 1)
  (turn-off-auto-fill)
  (turn-on-visual-line-mode)
  (visual-fill-column-mode 1)
  (setq! visual-fill-column-enable-sensible-window-split t
         visual-fill-column-width 100
         js-indent-level 2)
  (rainbow-delimiters-mode 1)
  (apheleia-mode -1))
(add-hook! 'json-mode-hook 'json-mode-tweaks)

(defun markdown-mode-tweaks ()
    (display-fill-column-indicator-mode 0)
    (mixed-pitch-mode 1)
    (+word-wrap-mode 0)
    (turn-off-auto-fill)
    (turn-on-visual-line-mode)
    (setq! visual-fill-column-enable-sensible-window-split t
           visual-fill-column-width 88
           adaptive-wrap-extra-indent 4)
    (visual-fill-column-mode 1)
    (adaptive-wrap-prefix-mode 1))
(add-hook! 'markdown-mode-hook 'markdown-mode-tweaks)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")

(after! org

(defun org-export-noignore-headlines (data _ info)
  "Remove headlines not tagged \"noignore\".
    The \"noignore\" tag marks headlines that will be retained.
    For all other headlines,contents are retained and any children headlines
    are promoted to the level of the parent."
  (org-element-map data 'headline
    (lambda (object)
      (when (not (member "noignore" (org-element-property :tags object)))
        (let ((level-top (org-element-property :level object))
              level-diff)
          (mapc (lambda (el)
                  ;; recursively promote all nested headlines
                  (org-element-map el 'headline
                    (lambda (el)
                      (when (equal 'headline (org-element-type el))
                        (unless level-diff
                          (setq level-diff (- (org-element-property :level el)
                                              level-top)))
                        (org-element-put-property el
                                                  :level (- (org-element-property :level el)
                                                            level-diff)))))
                  ;; insert back into parse tree
                  (org-element-insert-before el object))
                (org-element-contents object)))
        (org-element-extract-element object)))
    info nil)
  data)

(defun org-export-activate-ignore-headlines ()
  "Activates ignore-headlines and deactivates noignore-headlines"
  (ox-extras-deactivate '(noignore-headlines))
  (ox-extras-activate '(ignore-headlines)))

(defun org-export-activate-noignore-headlines ()
  "Deactivates ignore-headlines and activates noignore-headlines"
  (ox-extras-deactivate '(ignore-headlines))
  (ox-extras-activate '(noignore-headlines)))

(defun org-mode-minor-tweaks ()
    (org-indent-mode 0)
    (display-fill-column-indicator-mode 0)
    (mixed-pitch-mode 1)
    (+word-wrap-mode 0)
    (turn-off-auto-fill)
    (turn-on-visual-line-mode)
    (setq! visual-fill-column-enable-sensible-window-split t
           visual-fill-column-width 88
           adaptive-wrap-extra-indent 4)
    (visual-fill-column-mode 1)
    (adaptive-wrap-prefix-mode 1))
(add-hook! 'org-mode-hook 'org-mode-minor-tweaks)

(use-package! org-superstar ; "prettier" bullets
    :hook (org-mode . org-superstar-mode)
    :config
    ;; Make leading stars truly invisible, by rendering them as spaces!
    (setq org-superstar-leading-bullet ?\s
          org-superstar-leading-fallback ?\s
          org-hide-leading-stars nil
          org-superstar-todo-bullet-alist
          '(("TODO" . 9744)
            ("[ ]"  . 9744)
            ("DONE" . 9745)
            ("[X]"  . 9745))
          org-superstar-item-bullet-alist
          '((?* . ?•)
            (?+ . ?+)
            (?- . ?—))
          org-superstar-headline-bullets-list
          '("◈" "▣" "◉" "◆" "◾" "•")))

(use-package! org-fancy-priorities
    :hook (org-mode . org-fancy-priorities-mode)
    :hook (org-agenda-mode . org-fancy-priorities-mode)
    :config (setq org-fancy-priorities-list ' ("⚑" "⬆" "■")))

(setq org-ellipsis " ⌄"
        org-hide-emphasis-markers 1
        org-pretty-entities 1)

(setq-default org-display-custom-times nil)
(setq org-time-stamp-custom-formats
      '("​%A, %d %B, %Y​" . "​%A, %d %B, %Y, %H:%M %Z​")
      org-duration-format 'h:mm)

(setq! org-default-notes-file (concat org-directory "work.org"))

(setq org-todo-keywords
        '((sequence "TODO(t!)" "STRT(s!)" "TEST(u!)" "REVIEW(r!)" "|" "DONE(d!)")
          ;; Exceptional/alternate states
          (sequence "BLOCK(b@!)" "KNOWNCAUSE(c@!)" "ACCEPTANCE(R!)" "PUSH(p!)"
                    "|" "PUNT(P@!)" "CANCEL(k@!)")
          ;; Lightweight/subtask states
          (sequence "[ ](T)" "[-](S)" "[◆](U)" "[?](H)" "[!](B)" "|" "[✓](D)" "[X](K)")
          ;; Long-term/container states
          (sequence "LOOP(l)" "PROJ(j)" "IDEA(i)" "FEAT(f)" "|")))

(setq org-todo-keyword-faces
      '(("PROJ" . (:foreground "#fbf1c7" :weight bold))
        ("IDEA" . "#ebdbb2") ("[?]" ."#ebdbb2")
        ("FEAT" . "#458588")
        ("BUG" . "#fe8019")
        ("TODO" . "#d3869b") ("[ ]" . "#d3869b") ("LOOP" . "#b16286")
        ("STRT" . "#fabd2f") ("[-]" . "#fabd2f")
        ("PUSH" . "#fe8019")
        ("BLOCK" . "#cc241d") ("[!]" . "#cc241d")
        ("KNOWNCAUSE" . "#83a598") ("TEST" . "#83a598") ("[◆]" . "#83a598")
        ("REVIEW" . "#b8bb26") ("ACCEPTANCE" . "#b8bb26")
        ("PUNT" . "#928374") ("CANCEL" . "#928374") ("[X]" . "#928374")))

(setq! org-priority-highest ?A
       org-priority-lowest ?E
       org-priority-default ?C
       org-priority-faces
       '((?A . "#fb4934")
         (?B . "#fe8019")
         (?C . "#fabd2f")
         (?D . "#83a598")
         (?E . "#bdae93"))
       org-fancy-priorities-list
       '((?A . "‼")
         (?B . "⯅")
         (?C . "━")
         (?D . "⯆")
         (?E . "⯀")))

(setq org-capture-templates
      '(("t" "Todo" entry (file+headline "~/org/work.org" "INBOX")
         "* TODO [#B] %?\nSCHEDULED: %t\n:LOGBOOK:\n- State \"TODO\"       from \"\"           %U\n:END:"
         :empty-lines 0)
        ("T" "Personal todo" entry (file+headline "~/org/personal.org" "INBOX")
         "* TODO [#B] %?\nSCHEDULED: %t\n:LOGBOOK:\n- State \"TODO\"       from \"\"           %U\n:END:"
         :empty-lines 0)
        ("c" "Calendar event" entry (file+headline "~/org/work.org" "INBOX")
         "* %?\n%t")
        ("C" "Personal calendar event" entry (file+headline "~/org/work.org" "INBOX")
         "* %?\n%t")))

(setq org-log-into-drawer t
      org-agenda-skip-deadline-if-done t
      org-agenda-skip-deadline-prewarning-if-scheduled t
      org-agenda-skip-scheduled-if-deadline-is-shown t
      org-agenda-skip-scheduled-delay-if-deadline t
      org-agenda-skip-scheduled-if-done t)



)

(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :config
  :bind (:map copilot-completion-map
              ("<tab>" . 'copilot-accept-completion)
              ("TAB" . 'copilot-accept-completion)
              ("C-TAB" . 'copilot-accept-completion-by-word)
              ("C-<tab>" . 'copilot-accept-completion-by-word)))

(map! (:leader (:prefix "t"
                :desc "Apheleia mode" "a" #'apheleia-mode))
      (:leader (:prefix "t"
                :desc "Global Apheleia mode" "A" #'apheleia-global-mode))
      (:leader (:prefix "t"
                :desc "Visual Fill Column mode" "C" #'visual-fill-column-mode))
      (:leader (:prefix "t"
                :desc "Follow mode" "L" #'follow-mode))
      (:leader (:prefix "t"
                :desc "Golden ratio" "G" #'golden-ratio-mode))
      (:leader (:prefix "t"
                :desc "Variable pitch" "v" #'variable-pitch-mode))
      (:leader (:prefix "t"
                :desc "Rainbow mode" "R" #'rainbow-mode))
      (:leader (:prefix "t"
                :desc "Org LSP" "o" #'lsp-org))
      (:leader (:prefix "t"
                :desc "Mixed pitch mode" "M" #'mixed-pitch-mode)))

(map! (:leader
       (:prefix-map ("d" . "debugger")
        :desc "Launch GDB" "d" #'gdb
        :desc "Disassembly buffer" "a" #'gdb-display-disassembly-buffer
        :desc "GDB buffer" "g" #'gdb-display-gdb-buffer
        :desc "Registers buffer" "r" #'gdb-display-registers-buffer
        :desc "Source buffer" "s" #'gdb-display-source-buffer
        :desc "UI many windows" "m" #'gdb-many-windows)))

(map! (:leader
       (:prefix "w" (:prefix "g"
                     :desc "Resize to Golden Ratio" "g" #'golden-ratio))))

(map! (:leader (:prefix "c" :desc "Format buffer (apheleia)" "F" #'apheleia-format-buffer)))
